on: [push]

jobs:
  ipinfo:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: ipinfo
      id: ip
      uses: actions/nodejs_action@v1

    # Use the output from the `hello` step
    - name: Get the ip info 
      run: echo "The time was ${{ steps.ip.outputs.ipinf }}"
      # run: echo "The ip information is ${{ steps.ip.outputs.ipinf }}"
