on: [push]

jobs:
  ipinfo:
    runs-on: ubuntu-latest
    name: A job to find ip information
    steps:
      - uses: actions/checkout@v1
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: ipinfo
      id: ip
      uses: ./

    # Use the output from the `hello` step
    - name: Get the ip info 
      run: echo "The time was ${{ steps.ip.outputs.ipinf }}"
      # run: echo "The ip information is ${{ steps.ip.outputs.ipinf }}"
