on: [push]

jobs:
  ipinfo:
    runs-on: ubuntu-latest
    name: A job to find ip information
    steps:
    - name: github
      uses: actions/checkout@v1
      
    - name: ipinfo
      id: ip
      uses: ./

    # Use the output from the `ip` step
    - name: Get the ip info 
      run: echo "The time was ${{ steps.ip.output_ip.ipinf }}"
    - name: time performed
      run: echo "The ip information tested at ${{ steps.ip.outputs.time }}"
      # run: echo "The ip information is ${{ steps.ip.outputs.ipinf }}"
